### ISSUE TITLE
SYSTEM="" Is prompted as a literal reply to the user

### ISSUE THREAD

**Issue by xhyabunny** [238SAMIxD/discord-ai-bot#17]
SYSTEM prompt is replied to the user with no context even when asked not to.

**To Reproduce**
1. Write on SYSTEM="DO NOT WRITE THIS you are an assistant"
2. Use the .env system by marking USE_SYSTEM as true and USE_MODEL_SYSTEM as false
3. npm run
4. If you say something that the bot doesnt recognice properly, they will start prompting what you asked them not to prompt

**Expected behavior**
Bot using SYSTEM prompt as INFO on how to act 

**Device**
 - OS: Windows 10
 - Repo is latest (i downloaded as zip -> [c6af204](https://github.com/mekb-turtle/discord-ai-bot/commit/c6af20436a41982c81fa31e1c03311a1cff9336d))
 - Ollama version 0.1.29 (windows preview)

**Comment by hermitbernard** [comment]
I experienced the same, however I think this is more due to the llm than the bot. If you use the bot system prompt feature, what is happening is just that you are sending that as a prompt, so there’s a chance that the llm will take it from the context window and spit it out. 

I disabled the feature and instead rebuilt the model with my own system prompts using modelfiles, and since then I have never experienced this issue.

**Comment by xhyabunny** [comment]
okok tysm

**Comment by xhyabunny** [comment]
well i tried doing that but my bot now acts dry asf, like no personality at all, idk what that means

**Comment by hermitbernard** [comment]
It means you have to enrich the system prompt in the modelfile. Also make sure you set USE_SYSTEM_PROMPT=TRUE in the bot and that you are running the new model you just created.

**Comment by xhyabunny** [comment]
yeah

**Comment by sophuric** [comment]
what model are you using? some people have had issues with some models but llama2 seems to work for me

**Comment by 238SAMIxD** [comment]
I also cannot reproduce it (llama3). Closing for now
